### ISSUE TITLE
TH05Y_v3.1 with TH05_V1.4 screen - TEMPERATURE/HUMIDITY not working

### ISSUE THREAD

**Issue by Pinni3** [MakersFunDuck/humidity-temperature-sensor-TH05F#4]
Flashed the unit(s) did try the firmwares BOOT_TH05_vNN.hex And **BOOT_TH05F_vNN.hex**
Is a **TH05_V1.4 screen** with the marking **TH05Y_v3.1** on pcb , chipset is **QD01 2340 NT CJT 3353C**
After OTA No screen nor TEMP or humidity info , battery is displayed 
![image](https://github.com/user-attachments/assets/7b6d5165-2412-44e9-8240-65379e66494e)
![image](https://github.com/user-attachments/assets/483fad7f-b3f7-4fb8-b467-81c33bd3c579)

**BOOT_TH05F_v18.hex** is running atm but still no data for temp and humidity 
![image](https://github.com/user-attachments/assets/a13035a9-2c81-4ad8-9550-d7331fa6ea3c)
![image](https://github.com/user-attachments/assets/427819ca-9d61-43b2-a05d-dcdb41d4f7bb)

Is there a new firmware needed or coud this be adjusted with actions from my side?

**Comment by MakersFunDuck** [comment]
Hi,

I think this revision mosl likely have a different sensor. I do not have this pcb revision. can you check the temperature sensor on it, and write it down?

**Comment by s1lvi0** [comment]
I also have one of this board.

![20241210_122254](https://github.com/user-attachments/assets/60094c24-ecd0-4834-bc6e-0c9a09687dda)
![20241210_122225](https://github.com/user-attachments/assets/b28db61d-4d7f-4e16-aebb-2fa5e8f40311)
![20241210_122232](https://github.com/user-attachments/assets/42a15630-aa7d-40b0-9421-1f508b1dcbab)

**Comment by Pinni3** [comment]
https://github.com/pvvx/THB2/issues/84#issuecomment-2521891437
