### ISSUE TITLE
Error flashing FW under Win11

### ISSUE THREAD

**Issue by norcalbarney** [MakersFunDuck/humidity-temperature-sensor-TH05F#5]
I am having trouble flashing the boot firmware under Win11.
Steps:
git clone https://github.com/MakersFunDuck/humidity-temperature-sensor-TH05F.git
cd humidity-temperature-sensor-TH05F
python3 -m venv venv
venv\Scripts\activate
pip3 install -r requirements.txt
python3 rdwr_phy62x2.py -p COM7 -e -r wh ./bin/BOOT_TH05F_v18.hex

*error*  ModuleNotFoundError: No module named 'serial'

![Screenshot 2024-12-07 201718](https://github.com/user-attachments/assets/1ac0e703-f4f6-43ab-a6d5-38494e225719)

**Comment by MakersFunDuck** [comment]
hi, 
I think you might have skipped a step in the description.
did you tried: 
pip3 install -r requirements.txt
?

**Comment by MakersFunDuck** [comment]
alternatively, you can try 
pip install pyserial

**Comment by norcalbarney** [comment]
I did that step. It's in both my description and the screenshot.

(venv) D:\Software\humidity-temperature-sensor-TH05F>pip install pyserial
Requirement already satisfied: pyserial in d:\software\humidity-temperature-sensor-th05f\venv\lib\site-packages (3.5)

**Comment by MakersFunDuck** [comment]
Can you try :
python rdwr_phy62x2.py -p COM7 -e -r wh BOOT_XXX_vXX.hex
instead?

**Comment by norcalbarney** [comment]
(venv) D:\Software\humidity-temperature-sensor-TH05F>python rdwr_phy62x2.py -p COM7 -e -r wh BOOT_XXX_vXX.hex
PHY62x2 Utility version 11.03.24

Error: Open COM7, 9600 baud! Error: module 'serial' has no attribute 'Serial'

**Comment by MakersFunDuck** [comment]
Perhaps you have both pyserial  and serial libraries. can you try to uninstall both, and install just pyserial again?

sudo pip3 uninstall serial
sudo pip3 uninstall pyserial  
then
sudo pip3 install pyserial

**Comment by norcalbarney** [comment]
I am on Windows 11, so I skipped the sudos, but that did work!

I also totally uninstalled Python, Anaconda, miniconda, and python caches, then reinstalled Python.  But I am certain just uninstalling pyserial and serial was the winning step.

Thank you for your help, and for your work on this cool project!

**Comment by MakersFunDuck** [comment]
I'm glad I could help :)
